package studentdatabase;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class StudentDatabaseDriver {

    public static void main(String[] args) throws IOException {
        Scanner scan = new Scanner(System.in);
        System.out.print("Enter a file name to process: ");
        String fileName = scan.nextLine().trim();
        Scanner fileReader = new Scanner(new File(fileName));

        String s; // Stores the next line in the file temporarily

        StudentDatabase studentDB = new StudentDatabase(); // Creates an ArrayList to store Students and their information
        Prize[] prizeList = new Prize[10]; // Creates a new Array of Prizes. Maximum of 10 prizes per file.
        while (fileReader.hasNextLine()) { // Loop continues while there is more information in the file
            s = fileReader.nextLine();
            if (s.length() > 0) { // Ignores any blank lines in the file
                switch (s.charAt(0)) { // Checks the first character of the line in the file that is being read
                    case 'A', 'M', 'S' -> { // Adds a new Student to the studentDatabase
                        studentDB.addStudent(s);
                    } // case 'A', 'M', 'S'
                    case 'R' -> { // Adds a Result to a Student's results ArrayList
                        studentDB.addResult(s);
                    } // case 'R'
                    case 'P' -> {
                        studentDB.addPrize(s);
                    } // case 'P'
                    default -> { // defaults to doing nothing if above cases aren't met
                    } // default
                } // switch
            } // if
        } // while

        studentDB.awardPrize(); // Allocates Prizes to eligible Students
        studentDB.printRecords(); // Prints the details of all Students in studentDatabase
    } // main
} // StudentDatabaseDriver

/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXX0OkxxddKMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkkNWNKOOkdOXXN00NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOolxOOkxk0KXXkdOOOK0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkodOKX0dxO00OkkodKXX00NMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xxxdododdoxkkkOO0dlxkkxdkOxOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxx0NXxodOK0doOXNNXX0k0XXOx0ko0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkOXNXX0xodxxddxkkOkxkxdkd:lON0dKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxd0K00XXOdOKK0kdxONWWWWKOXO:lO0dckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc;:ldxkxkOkkxdxkO0Oxddoxxcldo:lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOOdcccclolccloolollododdxxdll0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl',cxOkxxkOx:'':xOkxxkOkl''oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNXNKkodkOOkkOOOxoodxOOOkkOOkdookKNXXNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx..........................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx...........',,;::::,',;ccc::;;;...........xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.........,oOKKXXNNXK0KXNNNNNXNKo,.........xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.......'cokXNNNNNNNNNNNNNNNNNWXkoc'.......xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx........cdkKNNNNNNWWNNNNNNNNWWXko;........xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.......,ldk0KKKKKKKK00KKKKKKKK0kdc'.......xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx........,:cccccllllcllcclllccccc:'........xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'........................................'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk'........................................'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;........................................;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl...............,..',,...,...............lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,..........;;.'l:.:ol,.cl..;;..........,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo......':;.:dc;dxcdkxllko;od,.;:.......oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc..';,.:dolxOxk0OO00OO0kkOdcdd,.,;...cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc..;odldOOO00000000000000O0Ooldl,..cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl',cx00000000000000000000000Oxc;,lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkllx000000000000000000000000kolkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxlok00000000000000000000kolxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxooxO00000000000000OxooxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxoodkO0000000kdoox0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xdooddddoodx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kxxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMWNNNNNNNNNNNNNNNNNNNWNXK0OkxONMMMMMMWNKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK00OkxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMNOxl;,;;;;::cc::;;;cOXkl'...;0MMMMMNx;',lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'...;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMW0:....lO00000Od;'xWMNo...;0MMMMMXc...,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo...;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMNl...,OMMMMMMMM0cxWMWx...;0MMMMMWKxod0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx...;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMNo...,OMMMMMMMMWXNMMWx...;0MMMMMMMMMWWMMMMMMMMMMWMMMMMMWWWMMMMMMMMMMMMMMWWWMMWx...;KMMMMMMMMMWWWWMMMMMMMMMMMMMWMMMMWWWMMMMMMMMWWWWMMMMMMMMMMM
MMMMMMMMMNo...,OMMMMMMMXKNMMMWx...;0MMWXOxdollxNMMN0kdoolo0MN0dlc:clkXMMMMMMWXkolcclokKd...;KMMMMWKkolooolld0NMMNOxdolldKW0dl:ckNMWKkooooolloOWMMMMMMM
MMMMMMMMMNo...,OWWWWMWXolKMMMWx...;0MMWXOl'...cXMMN0x:...'xOc:llc'...cKMMMX0d,..,lxkxoc;...;KMMW0l'.;xKXKOc..:OWNOd,...,do,....;KNd,.,xKXKOc.cXMMMMMMM
MMMMMMMMMNo....;lllllc;.:KMMMWx...;0MMMMMNl...cXMMMMMO,...,:dXWMNd...'kWMXl'...;0WMMMWO,...;KMWO;..;0WMMMW0;..;0MMWx'...,lO0kdd0Nk'..cXMMMMNolKMMMMMMM
MMMMMMMMMNo....lkkkkkxo,:KMMMWx...;0MMMMMWd...cXMMMMM0;...,kWMMMM0,...xWWk'....xWMMMMMNl...;KMNl...'loooool,..'xWMMO'...cXMMMMMMMk'...ckKWMMNXWMMMMMMM
MMMMMMMMMNo...,OMMMMMMWkdXMMMWx...;0MMMMMWd...cXMMMMM0;...dWMMMMMK;...xWNo....,0MMMMMMWx...;KMK;...;kOOOOOOOOO0XWMMO'..'kWMMMMMMMNx,....':oOXWMMMMMMMM
MMMMMMMMMNo...,OMMMMMMMWNWMMMWx...;0MMMMMWd...cXMMMMM0;..'kMMMMMMK;...xWNo....,0MMMMMMWx...;KMK;...:KMMMMMMMMMMMMMMO'..,OMMMMMMMMMWXkl,.....,dXMMMMMMM
MMMMMMMMMNo...,OMMMMMMMMMMMMMWx...;0MMMMMWd...cXMMMMM0;..'kWMMMMMK;...xWWd. ..,OMMMMMMWd...;KMNl...'xWMMMMMMMMMMMMMO'..,OMMMMMMMMWWMMWX0dc....cXMMMMMM
MMMMMMMMMNo...,OMMMMMMMMMMMMMWx...;0MMMMMWo...cXMMMMM0,..'kMMMMMMK;...xWMO,....oNMMMMMK:...;KMWO;...,kWMMMMMMMMMMMMO'..,OMMMMMMMWkdXMMMMMWk,..,0MMMMMM
MMMMMMMMMXc...'kWMMMMMMMMMMMMWd...,OMMMMMNl...:KMMMMWO'...dWMMMMMO,...dNMNd;....l0XNXOl'...'xNWW0:...'l0NWMMWWNWMMWx...'kWMMMMMMWd,oXWMMMWO,..lXMMMMMM
MMMMMMN0xl,...':dkKWMMMMMMMNOd;...'cx0NXOo,...,lkKX0xc'...;dONN0kc'...;dOXNXOc'...,::lxo'..';oONMNkl;'.';cloooxXN0d:...':x0NMMMMMO;';odxdl;,:xXMMMMMMM
MMMMMMWXKKKKKKKKKKXWMMMMMMMNKKKKKKKKKXNNKKKKKKKKKXNXKKKKKKKKKNWXKKKKKKKKKNMMMWXOkkkOKWWXOO0KXXNWMMMWNKOkkxkO0KNWNKKKKKKKKKXNMMMMMWX0Okkxkk0XWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMN0KWMMMX0NMMMMMW0OKWMMX0XMMMMMMMMX0NMMMMMMN0KWMMMN0KWMMMMMWXOOOOKWMMMMMMMMXOkOOKWMMMMMMMMN0kkOXMMMMMMMWK0NMMMMMMN0OkkOOKWMMMMWK0NMMWK0NMMMMMMM
MMMMMMMMK:lNMMWd:0MMMMMK:.;xNWk;xWMMMMMMWx;kMMMMMMNo;kWMWx:xWMMMMMWd,lxk0WMMMMMMMWd,lxl;xNMMMMMMKc:dkkXMMMMMMMNo:0MMMMMMXkd:'lxONMMMMW0:lKNk:dNMMMMMMM
MMMMMMMM0:lNMMWo;OMMMMMK:;c;oXx,xWMMMMMMWd;kMMMMMMMKc:0WO;oNMMMMMMWd,lkOKWMMMMMMMWd,oOo:xWMMMMMM0c;okKWMMMMMMMNl;0MMMMMMMMNo;OMMMMMMMMWO:co:dNMMMMMMMM
MMMMMMMMK:lXMMNo;0MMMMMK:lKx;cc,xWMMMMMMWd;kMMMMMMMWO;cx:cKMMMMMMMWd'lkkKWMMMMMMMWd',,:OWMMMMMMMMXOxl;dNMMMMMMNl;0MMMMMMMMNo;OMMMMMMMMMWO;'dNMMMMMMMMM
MMMMMMMMNo;okOd:oXMMMMMK:lNWO:.'xWMMMMMMWx;kMMMMMMMMWx,':0WMMMMMMMWd,oOOKWMMMMMMMWd;xkcl0WMMMMMMN0OOo;oNMMMMMMNl;0MMMMMMMMNo;OMMMMMMMMMMNl;0MMMMMMMMMM
MMMMMMMMMN0xxxx0NMMMMMMNO0WMMXkxKMMMMMMMMKOXMMMMMMMMMNOx0WMMMMMMMMWKxxkk0WMMMMMMMWKOXWXk0WMMMMMMNOxxx0NMMMMMMMW0ONMMMMMMMMWKOXMMMMMMMMMMW0ONMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 */
